// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD14WpRPi8MfikEm0PgRLaPJ1FgigMEhX8',
    appId: '1:970763120875:web:01811f9f6cd3e086c24eae',
    messagingSenderId: '970763120875',
    projectId: 'ios-android-notification',
    authDomain: 'ios-android-notification.firebaseapp.com',
    storageBucket: 'ios-android-notification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgv-j_-cjkG58UF4Gk9M__f1X2dpoyev0',
    appId: '1:970763120875:android:1413af5631125179c24eae',
    messagingSenderId: '970763120875',
    projectId: 'ios-android-notification',
    storageBucket: 'ios-android-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI6qSxRwq5v2udG0gsyEKiV97VBwzJVrE',
    appId: '1:970763120875:ios:46b9b7d3ea1f21cac24eae',
    messagingSenderId: '970763120875',
    projectId: 'ios-android-notification',
    storageBucket: 'ios-android-notification.appspot.com',
    iosClientId: '970763120875-bt6vpc2i3ja7unhdp2lb9e4u4l7udfms.apps.googleusercontent.com',
    iosBundleId: 'com.example.iosNotificationAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI6qSxRwq5v2udG0gsyEKiV97VBwzJVrE',
    appId: '1:970763120875:ios:46b9b7d3ea1f21cac24eae',
    messagingSenderId: '970763120875',
    projectId: 'ios-android-notification',
    storageBucket: 'ios-android-notification.appspot.com',
    iosClientId: '970763120875-bt6vpc2i3ja7unhdp2lb9e4u4l7udfms.apps.googleusercontent.com',
    iosBundleId: 'com.example.iosNotificationAndroid',
  );
}
